//ACTIONS FOR GALLERY

export const GET_GALLERY_SUCCESS = "GET_GALLERY_SUCCESS";
export const GET_GALLERY_FAILURE = "GET_GALLERY_FAILURE";

export const GET_AUTHORS_ALBUMS_SUCCESS = "GET_AUTHORS_ALBUMS_SUCCESS";
export const GET_AUTHORS_ALBUMS_FAILURE = "GET_AUTHORS_ALBUMS_FAILURE";

export const ADD_IMAGE_SUCCESS = "ADD_IMAGE_SUCCESS";
export const ADD_IMAGE_FAILURE = "ADD_IMAGE_FAILURE";

export const DELETE_IMAGE_SUCCESS = "DELETE_IMAGE_SUCCESS";
export const DELETE_IMAGE_FAILURE =  "DELETE_IMAGE_FAILURE";

//ACTIONS FOR USERS

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const LOGOUT_USER = "LOGOUT_USER";
